@Library("shared-library") _

pipeline {
    agent any
    environment {
        CI = 'true'
        PATH = "/usr/local/bin:/usr/bin:/bin:/sbin"
    }
    stages {
        stage('Init') {
            steps {
                helloWorld(dayOfWeek: "Thursday", name: "John")
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'node:21.6.1'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'yarn && yarn build'
            }
        }
        stage('Containerise') {
            steps {
                script {
                    docker.withRegistry("https://index.docker.io/v1", "89b42c75-2ff6-4dea-9574-ec25ea4ff01f") {
                        sh "commit=${env.GIT_COMMIT} serviceName=tic-tac-toe docker-compose build"
                        // docker.build("${DOCKER_REGISTRY_NAMESPACE}/${appName}:${env.GIT_COMMIT}", 'app')
                    }
                    // dockerBuild.build("tic-tac-toe")
                    // dockerBuild.push("tic-tac-toe")
                }
            }
        }
    }
}