@Library("shared-library") _

pipeline {
    agent any
    environment {
        CI = 'true'
        PATH = "/usr/local/bin:/usr/bin:/bin:/sbin"
        APP_NAME="tic-tac-toe"
    }
    stages {
        stage('Init') {
            steps {
                helloWorld(dayOfWeek: "Thursday", name: "John")
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'node:21.6.1'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'yarn && yarn build'
            }
        }
        stage('Containerise') {
            steps {
                script {
                    dockerBuild.build(env.APP_NAME)
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    dockerBuild.push(env.APP_NAME)
                }
            }
        }
    }
}